version: '3.8'  # You can set the appropriate version based on your needs
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile-jenkins
    container_name: jenkins
    ports:
      - "8080:8080"   # Expose Jenkins UI on port 8080
      - "50000:50000" # Expose Jenkins agent port
    volumes:
      - jenkins_home:/var/jenkins_home  # Persist Jenkins data
      - /var/run/docker.sock:/var/run/docker.sock # Use the host's Docker socket
    user: root # Run as root to allow installation of packages

  django:
    build:
      context: "./Django Project/EMS"
    volumes:
      - "./Django Project/EMS:/app"
    ports:
      - "8000:8000"

  react:
    build:
      context: "./React App/emsfrontend"
    volumes:
      - "./React App/emsfrontend:/app"
    ports:
      - "3000:3000"

volumes:
  jenkins_home: