version: '3'

services:
  django:
    build:
      context: "./Django Project/EMS"
    volumes:
      - "./Django Project/EMS:/app"
    ports:
      - "8000:8000"

  react:
    build:
      context: "./React App/emsfrontend"
    volumes:
      - "./React App/emsfrontend:/app"
    ports:
      - "3000:3000"